import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

import { FoundationLab } from "../../src/foundation-lab/public.js";

test("foundation lab renders persistent semantic equivalents and keyboard-native controls", () => {
  const html = renderToStaticMarkup(<FoundationLab />);
  assert.match(html, /Exact Content Registry inspection/u);
  assert.match(html, /Registry-loaded world projection/u);
  assert.match(html, /Deterministic Instruction artifacts/u);
  assert.match(html, /Readable source \(non-executable\)/u);
  assert.match(html, /Executable clause/u);
  assert.match(html, /Instruction approach tradeoffs/u);
  assert.match(html, /Compare prose-only variant/u);
  assert.match(html, /Inspect Policy conflict/u);
  assert.match(html, /Check degraded evidence/u);
  assert.match(html, /Finite Agent Context/u);
  assert.match(html, /Context Capacity:/u);
  assert.match(html, /Context category segments/u);
  assert.match(html, /Inspect exact Context manifest/u);
  assert.match(html, /Compare missing maintenance route/u);
  assert.match(html, /Step runtime Context growth/u);
  assert.match(html, /Trigger Strict overflow/u);
  assert.match(html, /Apply Keep Newest/u);
  assert.match(html, /utilization is not a quality score/u);
  assert.match(html, /Memory, Trace, and historical replay/u);
  assert.match(html, /Phase 4 decision-cycle evidence/u);
  assert.match(html, /Unavailable to Agent/u);
  assert.match(html, /Inspect complete decision Trace/u);
  assert.match(html, /Step isolated historical replay/u);
  assert.match(html, /Apply Priority Retention/u);
  assert.match(html, /Externalize and retrieve Memory/u);
  assert.match(html, /Inspect retrieval miss/u);
  assert.match(html, /Inspect exact Trace events/u);
  assert.match(html, /Persistent Memory and Trace evidence/u);
  assert.match(html, /Gate physical state/u);
  assert.match(html, /Gate sensor/u);
  assert.match(html, /Invalid optional package diagnostics/u);
  assert.match(html, /Persistent foundation evidence/u);
  assert.match(html, /Run safe feeding/u);
  assert.match(html, /Try rejected stale command/u);
  assert.match(html, /Verify replay and pinned history/u);
  assert.match(html, /<button/u);
  assert.match(html, /role="status"/u);
});
