export const CANONICAL_GLOSSARY = Object.freeze([
  Object.freeze({ term: "Prompt", definition: "A task-specific instruction sent to an Agent for one job." }),
  Object.freeze({ term: "Skill", definition: "A reusable instruction bundle or capability invoked by name or reference." }),
  Object.freeze({ term: "System Prompt", definition: "Persistent, high-priority behavioral instructions for an Agent or agent class." }),
  Object.freeze({ term: "Context", definition: "All information loaded for an Agent’s current decision or task." }),
  Object.freeze({ term: "Context Budget", definition: "The maximum Context load available to an Agent." }),
  Object.freeze({ term: "Memory", definition: "Prior observations or task-derived state retained or retrieved for future work." }),
  Object.freeze({ term: "Tool", definition: "A deterministic action interface an Agent may invoke." }),
  Object.freeze({ term: "Eval", definition: "A deterministic scenario that asserts expected behavior or outcomes." }),
  Object.freeze({ term: "Eval Suite", definition: "A named, reusable collection of Evals." }),
  Object.freeze({ term: "Agent", definition: "An autonomous actor configured with instructions, Context, Memory, and Tools." }),
  Object.freeze({ term: "Manager Agent", definition: "An Agent authorized to assign, coordinate, supervise, and escalate worker tasks." }),
  Object.freeze({ term: "Orchestration", definition: "The design of delegation, Context routing, concurrency, escalation, and reporting among Agents." }),
  Object.freeze({ term: "Trace", definition: "The structured record of inputs, selected clauses, Tool calls, and world-state changes." }),
  Object.freeze({ term: "Deploy", definition: "Make a versioned Prompt, Skill, System Prompt, or Agent configuration active." }),
]);
